# Generated by Django 4.2.11 on 2024-03-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0002_marker_description_marker_hyperlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
