# Generated by Django 4.2.11 on 2024-03-31 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0003_marker_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='city',
        ),
    ]
