# Generated by Django 4.2.11 on 2024-04-01 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('markers', '0005_marker_created_at_marker_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
        migrations.AddField(
            model_name='marker',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categories.city'),
        ),
    ]
